# Generated by Django 2.2.5 on 2020-03-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='article_ready',
            field=models.CharField(default='yes', max_length=3, verbose_name='Interested to publish article?'),
            preserve_default=False,
        ),
    ]
