# Generated by Django 2.2.5 on 2020-03-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200301_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='article_ready',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default=None, max_length=3, verbose_name='Interested to publish article?'),
        ),
    ]
