# Generated by Django 2.2.5 on 2020-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200301_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='article_ready',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='Interested to publish article?'),
        ),
    ]
