# Generated by Django 2.2.5 on 2020-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200219_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_photo',
            field=models.ImageField(blank=True, upload_to='author-photos/'),
        ),
    ]
